version: '3'

networks:
  application:
    driver: bridge

services:

  #Mysql service
  mysql:
    image: 'mysql:8.0'
    container_name: '${DOCKER_PREFIX}_mysql'
    restart: always
    ports:
      - '${DB_OUTSIDE_PORT}:3306'
    tty: true
    volumes:
      - './.docker/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    networks:
      - application

  #Redis service
  redis:
    image: 'redis:alpine'
    container_name: '${DOCKER_PREFIX}_redis'
    restart: always
    ports:
      - '${REDIS_OUTSIDE_PORT}:6379'
    volumes:
      - './.docker/redis:/data'
    networks:
      - application

  #Nginx service
  nginx:
    build:
      context: './.docker/nginx'
    restart: always
    container_name: '${DOCKER_PREFIX}_nginx'
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
      - '${NGINX_HOST_HTTPS_PORT}:443'
    environment:
      - APP_SERVER_DOMAIN=${APP_SERVER_DOMAIN}
      - APP_CLIENT_DOMAIN=${APP_CLIENT_DOMAIN}
    volumes:
      - './src:/var/www'
      - './.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './.docker/nginx/sites:/etc/nginx/sites'
      - './.docker/nginx/sites-available:/etc/nginx/sites-available'
      - './.docker/nginx/log:/var/log/nginx'
    depends_on:
      - mysql
      - php
    networks:
      - application

  #php service
  php:
    build:
      context: './.docker/php'
    container_name: '${DOCKER_PREFIX}_php'
    volumes:
      - './src/server:/var/www/server'
      - './src/client:/var/www/client'
    ports:
      - '9000:9000'
    networks:
      - application
